services:
  - type: web
    name: product-listing-backend
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_PATH
        value: /etc/secrets/firebase-service-account.json
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MASTER_ADMIN_KEY
        generateValue: true
